name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the Angular app
        run: npm run build -- --base-href="/route_tech_summit_task_ahmed_abdelhamid/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/browser/browser

      # Install Java (if needed)
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the Temurin distribution of OpenJDK
          java-version: '17'  # Specify the Java version needed

      # Package the build output into a WAR file
      - name: Package WAR file
        run: |
          cd dist/browser/browser
          jar -cvf test.war *

     # Create or update the production branch with the WAR file
      - name: Deploy WAR to production branch
        run: |
          git config --global user.name "ahmedabdelhamid404"
          git config --global user.email "ahmedsoftwaredev3@gmail.com"
          
          # Create a new branch or checkout the existing production branch
          git fetch origin
          git checkout -b production origin/production || git checkout --orphan production

          # Remove all files from the branch to ensure only the WAR file is present
          git rm -rf .
          
          # Copy the WAR file to the root directory of the production branch
          cp dist/browser/browser/test.war .

          # Add, commit, and push the WAR file to the production branch
          git add test.war
          git commit -m "Deploy WAR file to production branch"
          git push origin production
