name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the Angular app
        run: npm run build -- --base-href="/route_tech_summit_task_ahmed_abdelhamid/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/browser/browser

      # Install Java (if needed)
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the Temurin distribution of OpenJDK
          java-version: '17'  # Specify the Java version needed

      # Package the build output into a WAR file
      - name: Package WAR file
        run: |
          cd dist/browser/browser
          jar -cvf test.war *

      # Upload the WAR file as an artifact
      - name: Upload WAR file
        uses: actions/upload-artifact@v3
        with:
          name: your-angular-project.war
          path: dist/your-angular-project.war
